language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=x86
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository

script:
  # Unit Test
  - ./gradlew test
notifications:
  slack:
      on_success: always
      rooms:
        - werockstar:wl61Y86uYultyrQHTR3RE9Cx#ci_notify